/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meupaint;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JColorChooser;
import javax.swing.JComponent;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.KeyStroke;

/**
 *
 * @author Eddie
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    private Forma forma;

    JanelaPilhas janelaPilhas = new JanelaPilhas(this);

    Color VERDE = new Color(20, 115, 49);
    Color ORANGE = new Color(201, 94, 8);

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        ((DefaultEditor) ladosSpinner.getEditor()).getTextField().setEditable(false);
        registrarKeyBidings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        painelDesenho = new meupaint.PainelDesenho();
        labelLog = new java.awt.Label();
        panelFormas = new javax.swing.JPanel();
        btnPincel = new javax.swing.JToggleButton();
        btnBorracha = new javax.swing.JToggleButton();
        btnLinha = new javax.swing.JToggleButton();
        btnRetangulo = new javax.swing.JToggleButton();
        btnElipse = new javax.swing.JToggleButton();
        btnTriangulo = new javax.swing.JToggleButton();
        btnPoligono = new javax.swing.JToggleButton();
        ladosSpinner = new javax.swing.JSpinner();
        sliderContorno = new javax.swing.JSlider();
        painelContorno = new javax.swing.JPanel();
        painelPreenchimento = new javax.swing.JPanel();
        labelContorno = new javax.swing.JLabel();
        btnUndo = new javax.swing.JButton();
        btnRedo = new javax.swing.JButton();
        painelOpcoes = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        btnConfigs = new javax.swing.JButton();
        painelAvatar = new meupaint.PainelAvatar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Desenhador :3");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        painelDesenho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelDesenho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseDragged(evt);
            }
        });
        painelDesenho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                painelDesenhoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseReleased(evt);
            }
        });

        labelLog.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        labelLog.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelLog.setForeground(new java.awt.Color(255, 51, 51));
        labelLog.setText("Log de Formas:");
        labelLog.setVisible(false);

        javax.swing.GroupLayout painelDesenhoLayout = new javax.swing.GroupLayout(painelDesenho);
        painelDesenho.setLayout(painelDesenhoLayout);
        painelDesenhoLayout.setHorizontalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDesenhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLog, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelDesenhoLayout.setVerticalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDesenhoLayout.createSequentialGroup()
                .addContainerGap(508, Short.MAX_VALUE)
                .addComponent(labelLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelFormas.setBorder(javax.swing.BorderFactory.createTitledBorder("Formas"));

        buttonGroup.add(btnPincel);
        btnPincel.setSelected(true);
        btnPincel.setText("Pincel");
        btnPincel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPincelActionPerformed(evt);
            }
        });

        buttonGroup.add(btnBorracha);
        btnBorracha.setText("Borracha");
        btnBorracha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrachaActionPerformed(evt);
            }
        });

        buttonGroup.add(btnLinha);
        btnLinha.setText("Linha");
        btnLinha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinhaActionPerformed(evt);
            }
        });

        buttonGroup.add(btnRetangulo);
        btnRetangulo.setText("Retângulo");
        btnRetangulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetanguloActionPerformed(evt);
            }
        });

        buttonGroup.add(btnElipse);
        btnElipse.setText("Elipse");
        btnElipse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnElipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElipseActionPerformed(evt);
            }
        });

        buttonGroup.add(btnTriangulo);
        btnTriangulo.setText("Triângulo");

        buttonGroup.add(btnPoligono);
        btnPoligono.setText("Polígono");

        ladosSpinner.setModel(new javax.swing.SpinnerNumberModel(5, 3, null, 1));
        ladosSpinner.setToolTipText("Lados do Polígono Regular");
        ladosSpinner.setFocusCycleRoot(true);

        sliderContorno.setMaximum(10);
        sliderContorno.setMinimum(1);
        sliderContorno.setToolTipText("Tamanho do Contorno");
        sliderContorno.setValue(1);
        sliderContorno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sliderContorno.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderContornoStateChanged(evt);
            }
        });

        painelContorno.setBackground(new java.awt.Color(0, 0, 0));
        painelContorno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelContorno.setToolTipText("Cor do Contorno");
        painelContorno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        painelContorno.setPreferredSize(new java.awt.Dimension(20, 20));
        painelContorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelContornoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelContornoLayout = new javax.swing.GroupLayout(painelContorno);
        painelContorno.setLayout(painelContornoLayout);
        painelContornoLayout.setHorizontalGroup(
            painelContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        painelContornoLayout.setVerticalGroup(
            painelContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        painelPreenchimento.setBackground(new java.awt.Color(255, 255, 255));
        painelPreenchimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelPreenchimento.setToolTipText("Cor do Preenchimento");
        painelPreenchimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        painelPreenchimento.setPreferredSize(new java.awt.Dimension(20, 20));
        painelPreenchimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelPreenchimentoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelPreenchimentoLayout = new javax.swing.GroupLayout(painelPreenchimento);
        painelPreenchimento.setLayout(painelPreenchimentoLayout);
        painelPreenchimentoLayout.setHorizontalGroup(
            painelPreenchimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        painelPreenchimentoLayout.setVerticalGroup(
            painelPreenchimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        labelContorno.setText("1");

        btnUndo.setText("↩");
        btnUndo.setToolTipText("Desfazer");
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });

        btnRedo.setText("↪");
        btnRedo.setToolTipText("Refazer");
        btnRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormasLayout = new javax.swing.GroupLayout(panelFormas);
        panelFormas.setLayout(panelFormasLayout);
        panelFormasLayout.setHorizontalGroup(
            panelFormasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPincel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorracha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLinha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRetangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnElipse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTriangulo)
                .addGap(5, 5, 5)
                .addComponent(btnPoligono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ladosSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUndo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRedo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderContorno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelContorno, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelFormasLayout.setVerticalGroup(
            panelFormasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnLinha)
                    .addComponent(btnRetangulo)
                    .addComponent(btnElipse)
                    .addComponent(painelContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliderContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContorno)
                    .addComponent(btnTriangulo)
                    .addComponent(btnPoligono)
                    .addComponent(ladosSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUndo)
                    .addComponent(btnRedo)
                    .addComponent(btnPincel)
                    .addComponent(btnBorracha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRefresh.setText("Limpar Quadro");
        btnRefresh.setActionCommand("");
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnConfigs.setText("Depuração");
        btnConfigs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfigs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigsActionPerformed(evt);
            }
        });

        painelAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelAvatar.setToolTipText("Desenvolvido por EddiePricefield");
        painelAvatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelAvatarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelAvatarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout painelAvatarLayout = new javax.swing.GroupLayout(painelAvatar);
        painelAvatar.setLayout(painelAvatarLayout);
        painelAvatarLayout.setHorizontalGroup(
            painelAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );
        painelAvatarLayout.setVerticalGroup(
            painelAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelOpcoesLayout = new javax.swing.GroupLayout(painelOpcoes);
        painelOpcoes.setLayout(painelOpcoesLayout);
        painelOpcoesLayout.setHorizontalGroup(
            painelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOpcoesLayout.createSequentialGroup()
                .addComponent(painelAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfigs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelOpcoesLayout.setVerticalGroup(
            painelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConfigs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(painelAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelFormas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(painelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFormas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void painelDesenhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMousePressed

        if (btnLinha.isSelected()) {
            forma = new Linha(); //A linha é uma forma, então o objeto que a forma está apontando no Heap é do tipo Linha.
        } else if (btnRetangulo.isSelected()) {
            forma = new Retangulo(); //Caso selecione isso, ele começa a apontar para o objeto do tipo Retângulo
        } else if (btnElipse.isSelected()) {
            forma = new Elipse();
        } else if (btnTriangulo.isSelected()) {
            forma = new Triangulo();
        } else if (btnPoligono.isSelected()) {
            forma = new Poligono((int) (ladosSpinner.getValue()));
        } else if (btnPincel.isSelected()) {
            forma = new Pincel();
        } else if (btnBorracha.isSelected()) {
            forma = new Borracha();
        }

        forma.setTamanhoContorno(sliderContorno.getValue());
        forma.setX1(evt.getX());
        forma.setY1(evt.getY());
        forma.setContorno(painelContorno.getBackground());
        forma.setPreenchimento(painelPreenchimento.getBackground());

    }//GEN-LAST:event_painelDesenhoMousePressed

    private void painelDesenhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseReleased

        forma.setX2(evt.getX());
        forma.setY2(evt.getY());
        painelDesenho.addFormaTemp(forma);
        painelDesenho.setFormaTemp(null);
        labelLog.setForeground(VERDE);
        labelLog.setText("Desenhou: " + painelDesenho.getLastForma().getClass().getSimpleName());

        janelaPilhas.setFormaDesfazer(painelDesenho.getLastForma().getClass().getSimpleName());
        janelaPilhas.setFormaRefazer("");

        painelDesenho.repaint();
        atualizarPilhas();

    }//GEN-LAST:event_painelDesenhoMouseReleased

    private void painelDesenhoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseDragged
        
        forma.setX2(evt.getX());
        forma.setY2(evt.getY());

        painelDesenho.setFormaTemp(forma);

        painelDesenho.repaint();

    }//GEN-LAST:event_painelDesenhoMouseDragged

    private void btnRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetanguloActionPerformed

    private void btnLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLinhaActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        painelDesenho.limparListas();
        labelLog.setForeground(Color.red);
        labelLog.setText("Limpou o Quadro de Desenho");

        if (painelDesenho.getStackTamanho(1) == 0 && painelDesenho.getStackTamanho(3) == 0) {
            janelaPilhas.setFormaDesfazer("");
        } else {
            janelaPilhas.setFormaDesfazer("RedesenharTudo");
        }

        janelaPilhas.setFormaRefazer("");

        atualizarPilhas();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElipseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnElipseActionPerformed

    private void painelContornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelContornoMouseClicked

        Color c = JColorChooser.showDialog(
                this,
                "Cor do Contorno",
                painelContorno.getBackground());

        if (c != null) {
            painelContorno.setBackground(c);

        }

    }//GEN-LAST:event_painelContornoMouseClicked

    private void painelPreenchimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelPreenchimentoMouseClicked

        Color c = JColorChooser.showDialog(
                this,
                "Cor do Preenchimento",
                painelPreenchimento.getBackground());

        if (c != null) {
            painelPreenchimento.setBackground(c);
        }

    }//GEN-LAST:event_painelPreenchimentoMouseClicked

    private void sliderContornoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderContornoStateChanged

        labelContorno.setText((String.valueOf(sliderContorno.getValue())));

    }//GEN-LAST:event_sliderContornoStateChanged

    private void btnConfigsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigsActionPerformed

        janelaPilhas.setVisible(true);

    }//GEN-LAST:event_btnConfigsActionPerformed

    private void painelAvatarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelAvatarMouseEntered

        painelAvatar.setImagemParada(false);
        painelAvatar.repaint();

    }//GEN-LAST:event_painelAvatarMouseEntered

    private void painelAvatarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelAvatarMouseExited

        painelAvatar.setImagemParada(true);
        painelAvatar.repaint();

    }//GEN-LAST:event_painelAvatarMouseExited

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        painelDesenho.desfazer();

        if (painelDesenho.retornarEstado() == 1) {
            labelLog.setForeground(ORANGE);
            labelLog.setText("Desfez o Limpar Quadro");
        } else if (painelDesenho.retornarEstado() == 2) {
            labelLog.setForeground(ORANGE);
            labelLog.setText("Desfez: " + painelDesenho.redoFormaPeek().getClass().getSimpleName());
        }
        atualizarDesenhosPilhas();
        atualizarPilhas();

    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedoActionPerformed
        painelDesenho.refazer();

        if (painelDesenho.retornarEstado() == 3) {
            labelLog.setForeground(Color.BLUE);
            labelLog.setText("Refez o Limpar Quadro");
        } else if (painelDesenho.retornarEstado() == 4) {
            labelLog.setForeground(Color.BLUE);
            labelLog.setText("Refez: " + painelDesenho.undoFormaPeek().getClass().getSimpleName());
        }
        atualizarDesenhosPilhas();
        atualizarPilhas();

    }//GEN-LAST:event_btnRedoActionPerformed

    private void btnPincelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPincelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPincelActionPerformed

    private void btnBorrachaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrachaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrachaActionPerformed

    public void visibilidadeLog(boolean valor) {
        labelLog.setVisible(valor);
        labelLog.revalidate();
    }

    public void ativarLimparAlternativo(boolean valor) {
        if (valor) {
            painelDesenho.setLimparAlternativo(true);
        } else {
            painelDesenho.setLimparAlternativo(false);
        }
    }

    public int tamanhoStacks(int stackNum) {
        return painelDesenho.getStackTamanho(stackNum);
    }

    public void atualizarPilhas() {
        if (janelaPilhas != null) {
            janelaPilhas.repaint(); // redesenha a janela inteira
        }
    }

    private void atualizarDesenhosPilhas() {

        if (painelDesenho.getStackTamanho(1) > 0) {
            janelaPilhas.setFormaDesfazer(painelDesenho.undoFormaPeek().getClass().getSimpleName());
        } else if (painelDesenho.getStackTamanho(3) > 0) {
            janelaPilhas.setFormaDesfazer("RedesenharTudo");
        } else {
            janelaPilhas.setFormaDesfazer("");
        }

        if (painelDesenho.getStackTamanho(2) > 0) {
            janelaPilhas.setFormaRefazer(painelDesenho.redoFormaPeek().getClass().getSimpleName());
        } else if (painelDesenho.getStackTamanho(4) > 0) {
            janelaPilhas.setFormaRefazer("LimparTudo");
        } else {
            janelaPilhas.setFormaRefazer("");
        }

    }

    public void limparStacks() {
        painelDesenho.limparStacks();
    }

    private void registrarKeyBidings() {
        InputMap im = painelDesenho.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = painelDesenho.getActionMap();

        im.put(KeyStroke.getKeyStroke(KeyEvent.VK_Z, KeyEvent.CTRL_DOWN_MASK), "desfazer");
        im.put(KeyStroke.getKeyStroke(KeyEvent.VK_Y, KeyEvent.CTRL_DOWN_MASK), "refazer");

        am.put("desfazer", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                painelDesenho.desfazer();

                if (painelDesenho.retornarEstado() == 1) {
                    labelLog.setForeground(ORANGE);
                    labelLog.setText("Desfez o Limpar Quadro");
                } else if (painelDesenho.retornarEstado() == 2) {
                    labelLog.setForeground(ORANGE);
                    labelLog.setText("Desfez: " + painelDesenho.redoFormaPeek().getClass().getSimpleName());
                }
                atualizarDesenhosPilhas();
                atualizarPilhas();
            }
        });

        am.put("refazer", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                painelDesenho.refazer();

                if (painelDesenho.retornarEstado() == 3) {
                    labelLog.setForeground(Color.BLUE);
                    labelLog.setText("Refez o Limpar Quadro");
                } else if (painelDesenho.retornarEstado() == 4) {
                    labelLog.setForeground(Color.BLUE);
                    labelLog.setText("Refez: " + painelDesenho.undoFormaPeek().getClass().getSimpleName());
                }
                atualizarDesenhosPilhas();
                atualizarPilhas();
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBorracha;
    private javax.swing.JButton btnConfigs;
    private javax.swing.JToggleButton btnElipse;
    private javax.swing.JToggleButton btnLinha;
    private javax.swing.JToggleButton btnPincel;
    private javax.swing.JToggleButton btnPoligono;
    private javax.swing.JButton btnRedo;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JToggleButton btnRetangulo;
    private javax.swing.JToggleButton btnTriangulo;
    private javax.swing.JButton btnUndo;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel labelContorno;
    private java.awt.Label labelLog;
    private javax.swing.JSpinner ladosSpinner;
    private meupaint.PainelAvatar painelAvatar;
    private javax.swing.JPanel painelContorno;
    private meupaint.PainelDesenho painelDesenho;
    private javax.swing.JPanel painelOpcoes;
    private javax.swing.JPanel painelPreenchimento;
    private javax.swing.JPanel panelFormas;
    private javax.swing.JSlider sliderContorno;
    // End of variables declaration//GEN-END:variables
}
