/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meupaint;

/**
 *
 * @author Eddie
 */
public class JanelaPilhas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaPilhas.class.getName());
    private JanelaPrincipal janelaPrincipal;
    
    /**
     * Creates new form JanelaPilhas
     */
    public JanelaPilhas(JanelaPrincipal principal) {
        initComponents();
        this.janelaPrincipal = principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkLog = new javax.swing.JCheckBox();
        checkLimparQuadro = new javax.swing.JCheckBox();

        setTitle("Depuração das Pilhas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        checkLog.setText("Exibir Log");
        checkLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLogActionPerformed(evt);
            }
        });

        checkLimparQuadro.setText("Ativar \"Limpar Quadro\" Alternativo");
        checkLimparQuadro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLimparQuadroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(checkLimparQuadro)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkLog)
                    .addComponent(checkLimparQuadro))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLogActionPerformed

        if(checkLog.isSelected()){
            janelaPrincipal.visibilidadeLog(true);
        }else{
            janelaPrincipal.visibilidadeLog(false);
        }
        
    }//GEN-LAST:event_checkLogActionPerformed

    private void checkLimparQuadroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLimparQuadroActionPerformed

    if(checkLimparQuadro.isSelected()){
        janelaPrincipal.ativarLimparAlternativo(true);
    }else{
        janelaPrincipal.ativarLimparAlternativo(false);
    }
// TODO add your handling code here:
    }//GEN-LAST:event_checkLimparQuadroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkLimparQuadro;
    private javax.swing.JCheckBox checkLog;
    // End of variables declaration//GEN-END:variables
}
